export const GET_PRODUCTS_INITIATE = 'GET_PRODUCTS_INITIATE';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_PRODUCTBYID_INITIATE = 'GET_PRODUCTBYID_INITIATE';
export const GET_PRODUCTBYID_SUCCESS = 'GET_PRODUCTBYID_SUCCESS';
export const GET_PRODUCTBYID_FAILURE = 'GET_PRODUCTBYID_FAILURE';

export const ADD_PRODUCT_INITIATE = 'ADD_PRODUCT_INITIATE';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCTS_FAILURE = 'ADD_PRODUCTS_FAILURE';

export const DELETE_PRODUCT_INITIATE = 'DELETE_PRODUCT_INITIATE';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCTS_FAILURE = 'DELETE_PRODUCTS_FAILURE';